//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentacionDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesasPorSalon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MesasPorSalon()
        {
            this.Pedidos = new HashSet<Pedidos>();
        }
    
        public int ID { get; set; }
        public int Salon { get; set; }
        public int Mesa { get; set; }
        public bool Libre { get; set; }
    
        public virtual Mesas Mesas { get; set; }
        public virtual Salones Salones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
    }
}
