//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentacionDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int ID { get; set; }
        public int MesaSalon { get; set; }
        public int Plato { get; set; }
        public string Adicional1 { get; set; }
        public string Adicional2 { get; set; }
        public string Adicional3 { get; set; }
    
        public virtual MesasPorSalon MesasPorSalon { get; set; }
        public virtual Platos Platos { get; set; }
    }
}
