//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentacionDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Platos()
        {
            this.Pedidos = new HashSet<Pedidos>();
        }
    
        public int ID { get; set; }
        public string NombrePlato { get; set; }
        public int TipoPlato { get; set; }
        public int Cheff { get; set; }
        public System.TimeSpan TiempoPreparacion { get; set; }
        public string RutaFoto { get; set; }
    
        public virtual Cheffs Cheffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        public virtual PlatosTipos PlatosTipos { get; set; }
    }
}
